name: Build
permissions:
  contents: write
  id-token: write
  packages: write
on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:
jobs:
  prebuild:
    name: Prebuild Modules
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        if: matrix.os == 'windows-latest'
      - name: Install CUPS
        run: |
          sudo apt install libcups2-dev
        if: matrix.os == 'ubuntu-latest'
        shell: bash
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_BUILD_VERSION }}
          cache: "npm"
      - name: Prebuild
        run: |
          npm install --ignore-scripts
          mapfile -t node_versions <<< "$NODE_TARGET_VERSIONS"
          for target in "${node_versions[@]}"; do
            echo "Building for $target"
            npx prebuildify -t $target --no-napi --strip
          done
        shell: bash
        env:
          NODE_TARGET_VERSIONS: ${{ vars.NODE_TARGET_VERSIONS }}
      - name: Upload Prebuilds
        uses: actions/upload-artifact@v4
        with:
          name: prebuilds-${{ matrix.os }}
          path: prebuilds/
          if-no-files-found: error
          retention-days: 30
  package:
    name: Package
    runs-on: ubuntu-latest
    needs: prebuild
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_BUILD_VERSION }}
          registry-url: https://npm.pkg.github.com/
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Download Posix Prebuilds
        uses: actions/download-artifact@v4
        with:
          name: prebuilds-ubuntu-latest
          path: prebuilds/
      - name: Download Windows Prebuilds
        uses: actions/download-artifact@v4
        with:
          name: prebuilds-windows-latest
          path: prebuilds/
      - name: Package
        run: |
          mkdir -p dist
          npm pack --pack-destination dist
        shell: bash
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: ${{ github.ref_name != 'master' }}
          generate_release_notes: true
          tag_name: ${{ steps.package-version.outputs.current-version }}
          files: |
            dist/*
      - name: Publish
        if: github.ref_name == 'master'
        run: npm publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
